export const WRITING_QUOTES = [
  "The first draft is just you telling yourself the story. – Terry Pratchett",
  "You can always edit a bad page. You can’t edit a blank page. – Jodi Picoult",
  "Start writing, no matter what. The water does not flow until the faucet is turned on. – Louis L’Amour",
  "Write what disturbs you, what you fear, what you have not been willing to speak about. Be willing to be split open. – Natalie Goldberg",
  "You don’t start out writing good stuff. You start out writing crap and thinking it’s good stuff, and then gradually you get better at it. – Octavia E. Butler",
  "The scariest moment is always just before you start. – Stephen King",
  "Write the kind of story you would like to read. People will give you all sorts of advice about writing, but if you are not writing something you like, no one else will like it either. – Meg Cabot",
  "Writing is its own reward. – Henry Miller",
  "If there's a book that you want to read, but it hasn't been written yet, then you must write it. – Toni Morrison",
  "We write to taste life twice, in the moment and in retrospect. – Anaïs Nin",
  "I write to discover what I know. – Flannery O'Connor",
  "There is no greater agony than bearing an untold story inside you. – Maya Angelou",
  "The role of a writer is not to say what we all can say, but what we are unable to say. – Anaïs Nin",
  "Writing is easy. All you have to do is cross out the wrong words. – Mark Twain",
  "A professional writer is an amateur who didn’t quit. – Richard Bach",
  "The art of writing is the art of discovering what you believe. – Gustave Flaubert",
  "Writing means sharing. – Edmund White",
  "Fill your paper with the breathings of your heart. – William Wordsworth",
  "One day I will find the right words, and they will be simple. – Jack Kerouac",
  "Don't tell me the moon is shining; show me the glint of light on broken glass. – Anton Chekhov",
  "I write because I have something to say. – John Steinbeck",
  "I write because I cannot help it, I am way too involved. – John Updike",
  "The discipline of writing something down is the first step toward making it happen. – Lee Iacocca",
  "You can make anything by writing. – C.S. Lewis",
  "The road to hell is paved with works-in-progress. – Philip Roth",
  "Write without looking back. – Samuel Johnson",
  "Words are, of course, the most powerful drug used by mankind. – Rudyard Kipling",
  "Writing is an act of faith, not a trick of grammar. – E.B. White",
  "A writer only begins a book. A reader finishes it. – Samuel Johnson",
  "A word after a word after a word is power. – Margaret Atwood",
  "The best time for planning a book is while you're doing the dishes. – Agatha Christie",
  "Writing is a socially acceptable form of schizophrenia. – E.L. Doctorow",
  "A writer must believe that what he is doing is the most important thing in the world. And he must hold to this illusion even when he knows it is not true. – John Steinbeck",
  "Write what should not be forgotten. – Isabel Allende",
  "Writing is thinking on paper. – William Zinsser",
  "Writers live twice. – Natalie Goldberg",
  "A good writer possesses not only his own spirit but also the spirit of his friends. – Friedrich Nietzsche",
  "I write because if I didn't, I would die. – William Faulkner",
  "Write hard and clear about what hurts. – Ernest Hemingway",
  "Either write something worth reading or do something worth writing. – Benjamin Franklin",
  "If you don't have time to read, you don't have the time (or the tools) to write. Simple as that. – Stephen King",
  "Writing is a form of therapy; sometimes I wonder how all those who do not write, compose, or paint can manage to escape the madness. – Graham Greene",
  "Good writing is clear thinking made visible. – Bill Wheeler",
  "The more you write, the better you write. – Ray Bradbury",
  "You have to write every single day of your life. You have to read, you have to analyze, you have to learn how to write. – Joseph Heller",
  "The writer's journey is a process of self-discovery. – Paulo Coelho",
  "A writer is someone for whom writing is more difficult than it is for other people. – Thomas Mann",
  "Writing is a way of talking without being interrupted. – Jules Renard",
  "There are no laws for the novel. There never have been, nor can there ever be. – Doris Lessing",
  "I write to live, and I live to write. – Michael Ondaatje",
  "The difference between the almost right word and the right word is really a large matter – it's the difference between the lightning bug and the lightning. – Mark Twain",
  "Writing is an exploration. You start from nothing and learn as you go. – E.L. Doctorow",
  "To survive, you must tell stories. – Umberto Eco",
  "A story is a way to say something that can't be said any other way. – Flannery O'Connor",
  "Writing is the only way I have to explain my own life to myself. – Pat Conroy",
  "Write what you know, and know what you write. – Mark Twain",
  "Words are, in my not-so-humble opinion, our most inexhaustible source of magic. – J.K. Rowling",
  "Writing is the geometry of the soul. – Plato",
  "The secret of getting ahead is getting started. – Mark Twain",
  "I write because I don't know what I think until I read what I've written. – Flannery O'Connor",
  "Keep writing. – Gloria Steinem",
  "To me, the greatest pleasure of writing is not what it's about, but the inner music that words make. – Truman Capote",
  "I write, therefore I am. – Saul Bellow",
  "If you want to change the world, pick up your pen and write. – Martin Luther",
  "The more you write, the more you discover what you know. – Roy Peter Clark",
  "Writing is a form of personal freedom. It frees us from the mass identity we see in the making of the world. – Don DeLillo",
  "Every writer I know has trouble writing. – Joseph Heller",
  "Writing is a way of preserving memory. – Jorge Luis Borges",
  "When you write, you create a world that didn’t exist before. – Neil Gaiman",
  "You never have to change anything if you can write well. – Robert Frost",
  "Words have no power to impress the mind without the exquisite horror of their reality. – Edgar Allan Poe",
  "The task of a writer consists in isolating that element of his experience which is common to all. – Samuel Johnson",
  "A writer's work is never done. – William Faulkner",
  "The pages are a mirror of the soul. – Anaïs Nin",
  "Every great writer is a great reader first. – Ralph Waldo Emerson",
  "I write to find out what I think. – Flannery O'Connor",
  "To write is to explore the depths of our own humanity. – Salman Rushdie",
  "In writing, you must kill your darlings. – William Faulkner",
  "Writing is a solitary act, but it creates connection. – Margaret Atwood",
  "When I write, I feel a freedom that no other art can give me. – Zadie Smith",
  "Writing is an adventure into the unknown. – Jeanette Winterson",
  "Good writing is supposed to evoke sensation in the reader—not the fact that it is raining, but the feeling of being rained upon. – Virginia Woolf",
  "The art of writing is the art of applying the seat of the pants to the seat of the chair. – Mary Heaton Vorse",
  "A writer is someone who can make something out of nothing. – Arthur Miller",
  "If you want to be a writer, you must do two things above all others: read a lot and write a lot. – Stephen King",
  "Words are containers for power; you choose what is inside them. – Joy Harjo",
  "Writing is the only thing that, when I do it, I don't feel I should be doing something else. – Gloria Steinem",
  "To write is to expose your deepest self. – Anaïs Nin",
  "A writer's work is never finished, only abandoned. – Ernest Hemingway",
  "You can only write what you truly know, and you must write with truth. – Ernest Hemingway",
  "A good writer is a good observer of life. – Robert Greene",
  "Words, once written, have a power of their own. – Judy Blume",
  "Every time I write, I discover something new about myself. – Maya Angelou",
  "Books are a uniquely portable magic. – Stephen King",
  "I write to create, to explore, and to understand. – Haruki Murakami",
  "To write well, one must first listen well. – Robert Frost",
  "The writer must have the courage to forget what he knows, in order to write what he never knew. – William Faulkner",
  "Writing is a tool for self-discovery. – Charles Bukowski",
  "Writing helps us make sense of the chaos of life. – Susan Sontag",
  "Words are the most powerful form of magic. – J.K. Rowling",
  "Writing, like any art, requires a constant commitment to self-improvement. – Stephen King",
  "If you want to be a writer, you must do two things above all others: read a lot and write a lot. – Stephen King"
];
